"""Agricultural and Farmer News Engine for Kisan Route.
Provides timely news on MSP, government subsidies, mandi trends, and agro-technology.
"""

import datetime

AGRI_NEWS_ITEMS = [
    {
        "id": 1,
        "category_hi": "सरकारी नीति व MSP",
        "category_en": "Govt Policy & MSP",
        "category_slug": "schemes",
        "icon": "🏛️",
        "badge_hi": "नवीनतम",
        "badge_en": "Latest",
        "title_hi": "रबी और खरीफ फसलों के न्यूनतम समर्थन मूल्य (MSP) में नई बढ़ोतरी मंजूर",
        "title_en": "Cabinet Approves Fresh Hike in Minimum Support Price (MSP) for Crops",
        "summary_hi": "केंद्रीय कैबिनेट ने गेहूं, चना और सरसों सहित प्रमुख फसलों के समर्थन मूल्य में ₹150 से ₹250 प्रति क्विंटल तक की बढ़ोतरी को मंजूरी दी।",
        "summary_en": "Union Cabinet approves ₹150 to ₹250 per quintal increase in MSP for wheat, gram, and mustard to ensure fair returns for farmers.",
        "detail_hi": "किसानों की आय में बढ़ोतरी और लागत की भरपाई के लिए केंद्र सरकार ने आगामी सीजन के लिए नई MSP दरें घोषित की हैं। गेहूं का समर्थन मूल्य ₹2,275 से बढ़ाकर ₹2,425 प्रति क्विंटल किया गया है। किसान अब अपनी नजदीकी खरीद केंद्र पर सीधे रजिस्ट्रेशन करा सकते हैं।",
        "detail_en": "To boost farmers' income and cover input costs, the government announced new MSP rates. Wheat MSP has been enhanced to ₹2,425/qtl. Farmers can register at nearby procurement centers for direct bank transfers.",
        "source": "PIB कृषि मंत्रालय (Ministry of Agriculture)",
        "time_hi": "आज, 10:15 AM",
        "time_en": "Today, 10:15 AM",
    },
    {
        "id": 2,
        "category_hi": "डिजिटल मंडी (e-NAM)",
        "category_en": "Digital Mandi (e-NAM)",
        "category_slug": "mandi",
        "icon": "📊",
        "badge_hi": "ट्रेंडिंग",
        "badge_en": "Trending",
        "title_hi": "ई-नाम (e-NAM) से 1,500 से अधिक मंडियां डिजिटल जुड़ीं, अंतर-राज्यीय बिक्री में 35% तेजी",
        "title_en": "Over 1,500 Mandis Integrated on e-NAM, Inter-State Trade Jumps by 35%",
        "summary_hi": "अब एक राज्य का किसान दूसरे राज्य के थोक व्यापारियों को ऑनलाइन बोली के माध्यम से सीधे अपनी उपज बेच पा रहा है।",
        "summary_en": "Farmers from Northern and Central belts are now selling directly to coastal and metro traders via digital single-window bidding.",
        "detail_hi": "राष्ट्रीय कृषि बाजार (e-NAM) पर डिजिटल भुगतान और गुणवत्ता जांच की नई सुविधाओं से किसानों को बिचौलियों के बिना अपनी उपज का 15-20% बेहतर भाव मिल रहा है। किसान रूट जैसे प्लेटफॉर्म इसे स्थानीय लॉजिस्टिक्स से जोड़ रहे हैं।",
        "detail_en": "With automated weighing and instant bank settlements on e-NAM, farmers are realizing 15-20% higher returns. Agro-logistics aggregators like Kisan Route are enabling fast truck connections.",
        "source": "AgriMarket Bulletin",
        "time_hi": "2 घंटे पहले",
        "time_en": "2 hours ago",
    },
    {
        "id": 3,
        "category_hi": "सौर ऊर्जा व सब्सिडी",
        "category_en": "Solar Power & Subsidy",
        "category_slug": "schemes",
        "icon": "☀️",
        "badge_hi": "सब्सिडी अलर्ट",
        "badge_en": "Subsidy Alert",
        "title_hi": "पीएम-कुसुम (PM-KUSUM) योजना: सोलर वाटर पंप पर 60% सरकारी अनुदान",
        "title_en": "PM-KUSUM Scheme: Up to 60% Financial Subsidy for Solar Irrigation Pumps",
        "summary_hi": "डीजल पंप से मुक्ति के लिए किसानों को 3HP, 5HP और 7.5HP के सोलर पंप लगाने पर केंद्र व राज्य सरकार से भारी छूट मिल रही है।",
        "summary_en": "Farmers can now replace expensive diesel generators with subsidized solar water pumps, cutting irrigation electricity costs to zero.",
        "detail_hi": "किसानों को केवल 10% लागत खुद देनी होती है, जबकि 60% सब्सिडी सरकार देती है और 30% बैंक ऋण के रूप में उपलब्ध होता है। अतिरिक्त सौर बिजली ग्रिड को बेचकर किसान हर साल ₹40,000 तक अतिरिक्त आमदनी भी कर सकते हैं।",
        "detail_en": "Farmers contribute only 10% of total cost, while 60% is paid as subsidy and 30% via bank credit. Excess solar power can be sold back to state DISCOMs for additional annual earnings.",
        "source": "नवीकरणीय ऊर्जा मंत्रालय (MNRE)",
        "time_hi": "आज, 08:30 AM",
        "time_en": "Today, 08:30 AM",
    },
    {
        "id": 4,
        "category_hi": "कृषि लॉजिस्टिक्स",
        "category_en": "Agri Logistics",
        "category_slug": "logistics",
        "icon": "🚚",
        "badge_hi": "माल भाड़ा छूट",
        "badge_en": "Freight Subsidy",
        "title_hi": "किसान रेल व ग्रीन एक्सप्रेस से फल-सब्जियों के परिवहन भाड़े पर 50% छूट जारी",
        "title_en": "50% Freight Subsidy Continued for Perishable Produce Transport via Kisan Rail",
        "summary_hi": "जल्दी खराब होने वाली फसलों जैसे टमाटर, प्याज, आलू और फलों को दूर की मंडियों तक भेजने पर केंद्र सरकार आधा भाड़ा दे रही है।",
        "summary_en": "Ministry of Food Processing continues 50% freight subsidy on rail and road transport for perishables to curb post-harvest losses.",
        "detail_hi": "ऑपरेशन ग्रीन्स योजना के तहत छोटे किसानों के समूहों और क्लस्टर्स को बड़े उपभोक्ता बाजारों (जैसे मुंबई, कोलकाता, दिल्ली) तक माल पहुंचाने में सीधा आर्थिक सहयोग मिल रहा है, जिससे मंडियों में माल सड़ने की समस्या 70% कम हुई है।",
        "detail_en": "Under Operation Greens, farmer clusters get direct reimbursement on freight to metropolitan mandis, reducing post-harvest spoilage by nearly 70%.",
        "source": "भारतीय रेलवे & खाद्य प्रसंस्करण",
        "time_hi": "कल शाम",
        "time_en": "Yesterday Evening",
    },
    {
        "id": 5,
        "category_hi": "आधुनिक कृषि तकनीक",
        "category_en": "Agri Technology",
        "category_slug": "tech",
        "icon": "💡",
        "badge_hi": "ड्रोन नीति",
        "badge_en": "Drone Policy",
        "title_hi": "किसान ड्रोन योजना: कीटनाशक और नैनो यूरिया छिड़काव के लिए नई गाइडलाइन्स जारी",
        "title_en": "Kisan Drone Mission: New Guidelines for Precision Spraying and Crop Assessment",
        "summary_hi": "ड्रोन से केवल 10 मिनट में 1 एकड़ खेत पर कीटनाशक और तरल नैनो यूरिया का समान छिड़काव संभव, समय और पानी की 80% बचत।",
        "summary_en": "Precision agriculture drones allow 1-acre crop spraying in under 10 minutes, cutting water usage by 80% and protecting farmer health.",
        "detail_hi": "कृषि विज्ञान केंद्रों (KVK) द्वारा महिला स्वयं सहायता समूहों और युवा किसानों को ड्रोन पायलट की ट्रेनिंग दी जा रही है। किसान समूह रेंट पर ड्रोन बुक करके प्रति एकड़ ₹350 के कम खर्च में अपनी फसल पर आधुनिक स्प्रे करा सकते हैं।",
        "detail_en": "Krishi Vigyan Kendras are training rural youth and FPOs as certified drone pilots. Farmers can rent spray drones at just ₹350 per acre.",
        "source": "ICAR रिसर्च नेटवर्क",
        "time_hi": "3 घंटे पहले",
        "time_en": "3 hours ago",
    },
    {
        "id": 6,
        "category_hi": "मौसम व फसल बुवाई",
        "category_en": "Weather & Sowing",
        "category_slug": "weather",
        "icon": "🌧️",
        "badge_hi": "फसल बुलेटिन",
        "badge_en": "Crop Bulletin",
        "title_hi": "अनुकूल मानसून से रबी फसलों की बुवाई में तेजी, दलहन और तिलहन की मांग मजबूत",
        "title_en": "Favorable Monsoon Showers Accelerate Rabi Sowing Across Northern & Central Belts",
        "summary_hi": "मिट्टी में पर्याप्त नमी के कारण सरसों, चना और जौ की बुवाई समय से पहले शुरू, विशेषज्ञों ने दी संतुलित खाद उपयोग की सलाह।",
        "summary_en": "Adequate soil moisture levels provide ideal sowing conditions for mustard, gram, and barley with positive yield expectations.",
        "detail_hi": "मौसम विभाग (IMD) के अनुसार इस वर्ष तापमान सामान्य रहने से अंकुरण दर 95% से अधिक रहने की उम्मीद है। कृषि वैज्ञानिकों ने किसानों को प्रमाणित बीजों का ही चयन करने और बीज उपचार (Seed Treatment) अवश्य करने की सलाह दी है।",
        "detail_en": "IMD forecasts favorable winter temperatures resulting in >95% seed germination rates. Scientists advise farmers to use certified seeds and proper bio-fertilizer treatment.",
        "source": "कृषि मौसम विज्ञान प्रभाग (IMD)",
        "time_hi": "आज, 11:00 AM",
        "time_en": "Today, 11:00 AM",
    },
]


def get_agri_news(category=None):
    """Return all or category-filtered agricultural news."""
    if category and category != "all":
        return [n for n in AGRI_NEWS_ITEMS if n["category_slug"] == category]
    return AGRI_NEWS_ITEMS
